#!/bin/bash

############################################
# this file is managed by puppet           #
# changes to this file will be overwritten #
############################################


if [ -e /sys/fs/cgroup/systemd ]; then
        case "$2" in
                up)
                              systemctl start ntpd.service
                              sudo ntpd -qg
                ;;
                down)
                              systemctl stop ntpd.service
                ;;
        esac
else
        if [ -e "/etc/rc.d/ntpd" ]; then
                case "$2" in
                        up)
                                rc.d start ntpd
                        ;;
                        down)
                                rc.d stop ntpd
                        ;;
                esac
        fi

fi
